name: Build Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Apple Platforms Action
      uses: EmilioPelaez/build-apple-platforms@main
      with:
        project: 'Example/HierarchyResponderExample.xcodeproj'
        scheme: 'HierarchyResponderExample'
        watch_scheme: 'HierarchyResponderExampleWatch'
