name: Build Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Apple Xcode Select
      uses: BoundfoxStudios/action-xcode-select@v1
      with:
        version: latest
        beta: false
    
    - name: Build iOS
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Example/HierarchyResponderExample.xcodeproj
        workspace:
        scheme: HierarchyResponderExample
        destination: generic/platform=iOS Simulator
        action: build

    - name: Build Mac
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Example/HierarchyResponderExample.xcodeproj
        scheme: HierarchyResponderExample
        destination: generic/platform=macOS
        action: build
        build-settings: CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Build Watch
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Example/HierarchyResponderExample.xcodeproj
        scheme: HierarchyResponderExampleWatch
        destination: generic/platform=watchOS Simulator
        action: build

    - name: Build Vision
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Example/HierarchyResponderExample.xcodeproj
        scheme: HierarchyResponderExample
        destination: generic/platform=visionOS Simulator
        action: build
