name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Apple Xcode Select
      uses: BoundfoxStudios/action-xcode-select@v1
      with:
        version: latest
        beta: false

    - name: Test
      uses: sersoft-gmbh/xcodebuild-action@v3
      with:
        project: Tests/HierarchyResponderTests.xcodeproj
        scheme: HierarchyResponderTests
        destination: platform=iOS Simulator,name=iPhone 15
        action: test
        derived-data-path: build
        enable-code-coverage: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
